export const coursesList = [
  {
    name: 'html_css_beginners',
    hours: 23,
    classes: 164,
    house: 'origamid.com',
  },
  {
    name: 'full_javascript',
    hours: 37,
    classes: 156,
    house: 'origamid.com',
  },
  {
    name: 'react_completo',
    hours: 18,
    classes: 108,
    house: 'origamid.com',
  },
  {
    name: 'ui_design_beginners',
    hours: 17,
    classes: 155,
    house: 'origamid.com',
  },
  {
    name: 'css_flexbox',
    hours: 3,
    classes: 25,
    house: 'origamid.com',
  },
  {
    name: 'css_gridlayout',
    hours: 5,
    classes: 34,
    house: 'origamid.com',
  },
  {
    name: 'typescript_beginners',
    hours: 11,
    classes: 74,
    house: 'origamid.com',
  },
  {
    name: 'react_typescript',
    hours: 5,
    classes: 39,
    house: 'origamid.com',
  },
  {
    name: 'vue_2',
    hours: 22,
    classes: 112,
    house: 'origamid.com',
  },
  {
    name: 'full_nestjs',
    hours: 21,
    classes: 163,
    house: 'udemy.com',
  },
  {
    name: 'next',
    hours: 11,
    classes: 78,
    house: 'origamid.com',
  },
  {
    name: 'scss_css',
    hours: 6,
    classes: 31,
    house: 'origamid.com',
  },
  {
    name: 'react_native',
    hours: 45,
    classes: 334,
    house: 'udemy.com',
  },
];
